# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 766057c3753862ac3ec01fceb0cd4bc2faed389f6a483cd9adc6054a6dd1aeabb969672521cc496c5753455a2cb01a45a64d0adf3770f6936b4f2a96ffcdfc30

test:
  secret_key_base: 5825674a6914dc69b4f0e6dedf7bac892b5b749638ed4627f9763351929555e7822640086556667155c9bf29070b5429d6045b5beb42ce145d4bf412c3c41ea1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
